#include <voice/alphabet/A.h>
#include <voice/alphabet/B.h>
#include <voice/alphabet/C.h>
#include <voice/alphabet/D.h>
#include <voice/alphabet/E.h>
#include <voice/alphabet/F.h>
#include <voice/alphabet/G.h>
#include <voice/alphabet/H.h>
#include <voice/alphabet/I.h>
#include <voice/alphabet/J.h>
#include <voice/alphabet/K.h>
#include <voice/alphabet/L.h>
#include <voice/alphabet/M.h>
#include <voice/alphabet/N.h>
#include <voice/alphabet/O.h>
#include <voice/alphabet/P.h>
#include <voice/alphabet/Q.h>
#include <voice/alphabet/R.h>
#include <voice/alphabet/S.h>
#include <voice/alphabet/T.h>
#include <voice/alphabet/U.h>
#include <voice/alphabet/V.h>
#include <voice/alphabet/W.h>
#include <voice/alphabet/X.h>
#include <voice/alphabet/Y.h>
#include <voice/alphabet/Z.h>
